name: Build and publish docker image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to registry
        run: |
          echo ${{github.token}} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: actions/checkout@v2
      - name: Build, tag, and push
        run: |
          docker build -t image .
          TAG=$(git rev-parse --short HEAD)
          docker tag image ghcr.io/artyom/post-pr-comment:$TAG
          docker push ghcr.io/artyom/post-pr-comment:$TAG
